name: CI pipline
on: push   
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: print hello world
              run: echo "Hello world"
            - name: show current time
              run: date
            - name: list files in current directory
              run: ls -la    
             
