name: CI pipline
on:
  schedule:
    - cron: '* * * * *' # Run every day at midnight   
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: print hello world
              run: echo "Hello world"
            - name: show current time
              run: date
            - name: list files in current directory
              run: ls -la  
            - name: print workflow event
              run: echo "${{ toJson(github.event_name )}}" 
            - name: refrence github context
              run: echo "The repository is ${{ github.repository }}"  
            - name: show github workspace
              run: echo "The github workspace is ${{ github.workspace }}"
            - name: show github os
              run: echo "The github os is ${{ runner.os }}"       
             
